@startuml
left to right direction
package "Sistema" as Blackbox {
  (Registrazione)
  (Visualizzazione PKB)
  (Filtraggio POSD)
  (Ricerca)
  (Segnalazione)
  (Login)
  (Feedback)
  (Gestione_profilo)
  (Visualizzazione_richieste_modifiche_PKB)
  (Registro_Modifiche)
  (Integrazione_Modifiche_PKB)
  (Gestione_PKB)
  (Visualizzazione_Utenti_registrati)
  (Rimozione_Utente)
}

actor Utente
actor Utente_registrato
actor Amministratore_di_sistema
actor CISO


Utente <|- Utente_registrato
Utente_registrato <|-Amministratore_di_sistema
Utente_registrato <|-CISO


Utente-->(Filtraggio POSD)
(Visualizzazione PKB)<..(Filtraggio POSD):extend
Utente --> (Registrazione)
Utente --> (Visualizzazione PKB)
Utente --> (Ricerca)

Utente_registrato-->(Segnalazione)
Utente_registrato-->(Login)
Utente_registrato-->(Feedback)
Utente_registrato-->(Gestione_profilo)


Amministratore_di_sistema-->  (Registro_Modifiche)
Amministratore_di_sistema-->(Visualizzazione_Utenti_registrati)
(Visualizzazione_Utenti_registrati)<..(Rimozione_Utente):extend
Amministratore_di_sistema-->(Gestione_PKB)
Amministratore_di_sistema-->(Integrazione_Modifiche_PKB)

CISO-->(Registro_Modifiche)
CISO-->  (Visualizzazione_richieste_modifiche_PKB)



@enduml
