@startuml
actor User
participant FlaskApp
participant conn_db

User -> FlaskApp: Richiesta di connessione al database
activate FlaskApp
FlaskApp -> conn_db: Connessione al database
activate conn_db
conn_db --> FlaskApp: Connessione stabilita
deactivate conn_db
FlaskApp --> User: Risposta con conferma di connessione
deactivate FlaskApp
@enduml
