@startuml
'https://plantuml.com/sequence-diagram


actor User
participant Browser
participant App
participant ProtectedRouteToken
participant ProtectedRouteRuolo
participant Profili


User -> Browser: Open App
Browser -> App: Initialize
App -> NavBar: Render NavBar with token
App -> Searchbar: Render Searchbar
App -> Home: Render Home

User -> Browser: Navigate to /Login
Browser -> App: Render Login Route
App -> Login: Render Login Component

User -> Browser: Navigate to /Profili
Browser -> App: Render Profili Route
App -> ProtectedRouteToken: Check Token
ProtectedRouteToken -> App: Token Valid
App -> Profili: Render Profili Component

User -> Browser: Navigate to /segnalazione/:id
Browser -> App: Render Segnalazione Route
App -> ProtectedRouteToken: Check Token
ProtectedRouteToken -> App: Token Valid
App -> SceltaSegnalazione: Render Scelta Segnalazione Component if ruolo == 'CISO'

User -> Browser: Navigate to /AggiungiSegnalazione/:id
Browser -> App: Render Aggiungi Segnalazione Route
App -> ProtectedRouteToken: Check Token
ProtectedRouteToken -> App: Token Valid
App -> ProtectedRouteRuolo: Check Ruolo
ProtectedRouteRuolo -> App: Ruolo Valid
App -> SegnalazioneAS: Render Aggiungi Segnalazione Component if ruolo == 'Amministratore di sistema'
@enduml
