@startuml
actor Utente
participant
participant conn_db

Utente -> FlaskApp: Richiesta di connessione al database


FlaskApp -> conn_db: Connessione al database
activate conn_db
conn_db --> FlaskApp: Connessione stabilita
deactivate conn_db
FlaskApp --> User: Risposta con conferma di connessione
deactivate FlaskApp
@enduml
