@startuml
'https://plantuml.com/sequence-diagram
actor User
participant Browser
participant App
participant ProtectedRouteToken
participant ProtectedRouteRuolo
participant Profili
User -> Browser: Navigate to /AggiungiSegnalazione/:id
Browser -> App: Render Aggiungi Segnalazione Route
App -> ProtectedRouteToken: Check Token
ProtectedRouteToken -> App: Token Valid
App -> ProtectedRouteRuolo: Check Ruolo
ProtectedRouteRuolo -> App: Ruolo Valid
App -> SegnalazioneAS: Render Aggiungi Segnalazione Component if ruolo == 'Amministratore di sistema'
@enduml