@startuml
'https://plantuml.com/sequence-diagram
actor User
participant  Browser
participant  App
participant  FilterPage
participant  PatternService
participant  PatternList

User -> Browser: Apri app
Browser -> App: Inizializzare
App -> FilterPage: Rendering FilterPage con opzioni di filtro

User -> FilterPage: Visualizza le opzioni di filtraggio
Utente -> FilterPage: seleziona i criteri di filtraggio
FilterPage -> PatternService: Richiedi modelli con criteri selezionati
PatternService -> PatternList: Ottieni criteri di corrispondenza dei modelli
PatternList -> PatternService: restituisce i modelli corrispondenti
PatternService -> FilterPage: restituisce modelli filtrati

FilterPage -> Utente: Visualizza modelli filtrati

@enduml
