@startuml
'https://plantuml.com/sequence-diagram


actor User
participant Browser
participant App
participant ProtectedRouteToken
participant ProtectedRouteRuolo
participant Login
participant Home
participant NavBar
participant Searchbar

User -> Browser: Open App
Browser -> App: Initialize
App -> NavBar: Render NavBar with token
App -> Searchbar: Render Searchbar
App -> Home: Render Home

User -> Browser: Navigate to /Login
Browser -> App: Render Login Route
App -> Login: Render Login Component

User -> Browser: Navigate to /Profili
Browser -> App: Render Profili Route
App -> ProtectedRouteToken: Check Token
ProtectedRouteToken -> App: Token Valid
App -> NavBar: Render NavBar with token
App -> Profili: Render Profili Component

User -> Browser: Navigate to /Partecipa
Browser -> App: Render Partecipa Route
App -> ProtectedRouteToken: Check Token
ProtectedRouteToken -> App: Token Valid
App -> ProtectedRouteRuolo: Check Ruolo
ProtectedRouteRuolo -> App: Ruolo Valid
App -> NavBar: Render NavBar with token
App -> Searchbar: Render Searchbar
App -> Partecipa: Render Partecipa Component

User -> Browser: Logout
Browser -> App: Call Logout
App -> LogOUT: Execute LogOUT
LogOUT -> App: Clear Token and Ruolo
@enduml



